<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChildrenProfilesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('children_profiles')->delete();
        DB::table('children_profiles')->insert([
           [
               'id'             =>1,
               'first_name'     =>'Nguyễn',
               'last_name'      =>'Hoàng Hiệp',
               'birthday'       =>'2010-07-10',
               'blood_group'    =>'A',
               'gender'         =>1,
               'date_of_joining'=>'2012-02-03',
               'unique_id'      =>'0OGV3MG58C',
               'address'        =>'116 Tran Cung Stree',
               'allergies'      =>'',
               'additional_note'=>'',
               'image'          =>'',
               'status'         =>1,
               'exist'          =>1,
               
           ],
            [
                'id'             =>2,
                'first_name'     =>'Hoàng',
                'last_name'      =>'Công Khánh',
                'birthday'       =>'2010-01-10',
                'blood_group'    =>'B',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'PAROD74HTR',
                'address'        =>'59-61 Nguyen Thai Hoc',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,
                
            ],
            [
                'id'             =>3,
                'first_name'     =>'Cao',
                'last_name'      =>'Minh Đức',
                'birthday'       =>'2010-02-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'34GF63FDF',
                'address'        =>'',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,
                
            ],
            [
                'id'             =>4,
                'first_name'     =>'Đồng',
                'last_name'      =>'Văn Hùng',
                'birthday'       =>'2010-03-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'45GFG343YY',
                'address'        =>'716 N9A, Linh Dam Peninsula, Hoang Liet Ward',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,
                
            ],
            [
                'id'             =>5,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Minh Hiếu',
                'birthday'       =>'2010-10-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-04-03',
                'unique_id'      =>'GDDWDS34SDD',
                'address'        =>'678 Truong Chinh St., Ward 15',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,
                
            ],
            [
                'id'             =>6,
                'first_name'     =>'Trương',
                'last_name'      =>'Tuấn Nghĩa',
                'birthday'       =>'2010-10-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-05-03',
                'unique_id'      =>'65HGJ87FD',
                'address'        =>'130/1490A Le Duc Tho, Ward 13',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,
                
            ],
            [
                'id'             =>7,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Tư Tỉnh',
                'birthday'       =>'2010-06-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'3534FSDSADS54',
                'address'        =>'223 Hung Vuong St.',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,
                
            ],
            [
                'id'             =>8,
                'first_name'     =>'Đoàn',
                'last_name'      =>'Ngọc Tân',
                'birthday'       =>'2010-07-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'ASD2323FDF',
                'address'        =>'196/18 To Hieu St., Hiep Tan Ward',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,
                
            ],
            [
                'id'             =>9,
                'first_name'     =>'Trần',
                'last_name'      =>'Thái Bảo',
                'birthday'       =>'2010-08-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'546GFSV5XC',
                'address'        =>'',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,
                
            ],
            [
                'id'             =>10,
                'first_name'     =>'Vũ',
                'last_name'      =>'Đình Tuyên',
                'birthday'       =>'2010-09-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'ACXV63H76SD',
                'address'        =>'4A Hoang Van Thu, Pleiku City',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,
                
            ],
            [
                'id'             =>11,
                'first_name'     =>'Trần',
                'last_name'      =>'Đình Giang',
                'birthday'       =>'2010-10-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'E1GZWHAM2I',
                'address'        =>'43/17 Su Van Hanh Str.[ext.], Ward 12, Dist.10',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>12,
                'first_name'     =>'Hoàng',
                'last_name'      =>'Hải Thành ',
                'birthday'       =>'2010-11-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'AA6PSTTGII',
                'address'        =>'94/438 Vinh Ho Lane, Thinh Quang Ward',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],
            [
                'id'             =>13,
                'first_name'     =>'Phùng',
                'last_name'      =>'Văn Trường',
                'birthday'       =>'2010-12-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'RC28AB7F8W',
                'address'        =>'43 Ban Co St., Ward 3, Dist. 3',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],
            [
                'id'             =>14,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Văn Dũng',
                'birthday'       =>'2010-10-01',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'GIISYRF1FJ',
                'address'        =>'153/15 Truong Dinh, Ward 9, Dist.3',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>15,
                'first_name'     =>'Đỗ',
                'last_name'      =>'Hoàng Trung',
                'birthday'       =>'2010-10-02',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'V82AWWWIZ9',
                'address'        =>'12C/3, Hoa Lan, Ward 2',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>16,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Duy Minh',
                'birthday'       =>'2010-10-03',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'1RWLTHEBUG',
                'address'        =>'157/14 Ho Van Hue St., Ward 9',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>17,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Hữu Khải',
                'birthday'       =>'2010-10-04',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'MEMPBMPLJN',
                'address'        =>'424 lane, Thuy Khue st.',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'432 Tran Phu',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>18,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Đình Thịnh',
                'birthday'       =>'2010-10-05',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'01O9RVFRLM',
                'address'        =>'424 lane, Thuy Khue st., Tay Ho Dist',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>19,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Văn Vũ',
                'birthday'       =>'2010-10-06',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'T6W3KUDDE8',
                'address'        =>'150/3, Group 2',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>20,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Sơn Nam',
                'birthday'       =>'2010-10-07',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'NVB6R8TSXE',
                'address'        =>'Building 16, Lane 310 Nghi Tam Street',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>21,
                'first_name'     =>'Phạm',
                'last_name'      =>'Mỹ Linh',
                'birthday'       =>'2010-10-08',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'LQDKS2P4GA',
                'address'        =>'30 Dong Da St.',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>22,
                'first_name'     =>'Hoàng',
                'last_name'      =>'Gia Lâm',
                'birthday'       =>'2010-10-09',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'VUKSN0D9VT',
                'address'        =>'553/60A Nguyen Kiem, Ward 9',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>23,
                'first_name'     =>'Phạm',
                'last_name'      =>'Trung Hiếu',
                'birthday'       =>'2010-10-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'E0SQKS1SDB',
                'address'        =>'18 Chuong Duong St., Linh Chieu Ward',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>24,
                'first_name'     =>'Chu',
                'last_name'      =>'Nhất Long',
                'birthday'       =>'2010-10-11',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'BGUIFETM29',
                'address'        =>'D20/537A Trinh Quang Nghi St., Hamlet 4, Phong Phu Ward',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>25,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Xuân Dương',
                'birthday'       =>'2010-10-12',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'9KGWWZ9H3K',
                'address'        =>'136/22 Dinh Tien Hoang, Ward 1',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>26,
                'first_name'     =>'Lê',
                'last_name'      =>'Thị Hương Trang',
                'birthday'       =>'2010-10-13',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'KFIGY4AKE6',
                'address'        =>'91 Nguyen Cu Trinh St., Nguyen Cu Trinh Ward, Dist. 1',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>27,
                'first_name'     =>'Trần',
                'last_name'      =>'Hào Phong',
                'birthday'       =>'2010-10-14',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'15TS0B90FE',
                'address'        =>'12C/3, Hoa Lan, Ward 2',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>28,
                'first_name'     =>'Đỗ',
                'last_name'      =>'Tiến Thành',
                'birthday'       =>'2010-10-15',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'5BJQK5EQHU',
                'address'        =>'Unit 302, 168 Ngoc Khanh St.',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>29,
                'first_name'     =>'Trần',
                'last_name'      =>'Minh Duyệt',
                'birthday'       =>'2010-10-16',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'EJCSD69QVS',
                'address'        =>'126 Nguyen Thi Minh Khai StreetDistrict 3',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>30,
                'first_name'     =>'Lê',
                'last_name'      =>'Thanh Độ',
                'birthday'       =>'2010-10-17',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'NWW2JNBD1P',
                'address'        =>'297 Ngo Gia Tu, Ward 3, Dist.10',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>31,
                'first_name'     =>'Vũ',
                'last_name'      =>'Hoàng Trung',
                'birthday'       =>'2010-10-18',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'QLSNFCC19V',
                'address'        =>'136/36 Nguyen Thi Tan Street, Ward 2, District 8',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>32,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Tuấn Hưng',
                'birthday'       =>'2010-10-19',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'4VR8NW0SBU',
                'address'        =>'81 Tran Minh Quyen Street, Ward 10, District 10',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>33,
                'first_name'     =>'Phạm',
                'last_name'      =>'Văn Tùng',
                'birthday'       =>'2010-10-20',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'7ONOD7K2AC',
                'address'        =>'148 Dien Bien Phu St.',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>34,
                'first_name'     =>'Vũ ',
                'last_name'      =>'Đình Tuyên',
                'birthday'       =>'2010-10-21',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'Y7571ATEW1',
                'address'        =>'19 Ngo Quyen St., Ward 7',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>35,
                'first_name'     =>'Vũ',
                'last_name'      =>'Minh Hiếu',
                'birthday'       =>'2010-10-22',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'U4UU702BZ8',
                'address'        =>'586 Ba Trieu StreetThanh Hoa city',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>36,
                'first_name'     =>'Thạch',
                'last_name'      =>'Thọ Hiếu',
                'birthday'       =>'2010-10-23',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'E4S0OJY9WS',
                'address'        =>'2C Tran Khanh Du Street, Tan Dinh Ward, District 1',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>37,
                'first_name'     =>'Phùng',
                'last_name'      =>'Văn Trường',
                'birthday'       =>'2010-10-24',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'FGHIPQLGH1',
                'address'        =>'10/2 Dang Van Ngu St., Ward 10',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>38,
                'first_name'     =>'Bùi',
                'last_name'      =>'Thị Nga',
                'birthday'       =>'2010-10-25',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'7KI1H1RT45',
                'address'        =>'8 Le Tan Quoc St., Ward 13',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>39,
                'first_name'     =>'Khổng',
                'last_name'      =>'Anh Dũng',
                'birthday'       =>'2010-10-26',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'EYNQEDH8GZ',
                'address'        =>'6F TS Building 17 No.2 street, Cu Xa Do Thanh, Ward 4 Dist. 3',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>40,
                'first_name'     =>'Đoàn',
                'last_name'      =>'Ngọc Tân',
                'birthday'       =>'2010-10-27',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'NJNI9JLX3Z',
                'address'        =>'2C Tran Khanh Du Street, Tan Dinh Ward, District 1',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>41,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Mạnh Quang',
                'birthday'       =>'2010-10-28',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'7YKIJA4RIL',
                'address'        =>'26 BC Phan Van Tri Street, Ward 7',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>42,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Việt Long',
                'birthday'       =>'2010-10-29',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'LFMGFY9YY3',
                'address'        =>'195 Ngo Tat To, Ward 22',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>43,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Sơn Hải',
                'birthday'       =>'2010-10-30',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'ATEMYBIUCH',
                'address'        =>'10J Tran Nhat Duat Street, Tan Dinh Ward, District 1',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>44,
                'first_name'     =>'Lê',
                'last_name'      =>'Quang Đức',
                'birthday'       =>'2010-10-31',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'ZMZ0RQ9L1K',
                'address'        =>'',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>45,
                'first_name'     =>'Trần',
                'last_name'      =>'Hào Phong',
                'birthday'       =>'2010-05-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'YT9RFGA66G',
                'address'        =>'36, Alley 1150, Lang Street',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>46,
                'first_name'     =>'Bùi',
                'last_name'      =>'Trung Anh',
                'birthday'       =>'2010-10-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-06-03',
                'unique_id'      =>'J0ZEOJDSJA',
                'address'        =>'422 Dong Den St., Bau Cat 1 Apt Blk, Ward 14',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>47,
                'first_name'     =>'Khuất',
                'last_name'      =>'Duy Tiến',
                'birthday'       =>'2010-07-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'IAM7AEGTOG',
                'address'        =>'27-29 Hai Ba Trung, Ben Nghe Ward',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>48,
                'first_name'     =>'Nguyễn',
                'last_name'      =>'Việt Long',
                'birthday'       =>'2010-08-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'LQTE7J4UB6',
                'address'        =>'8 Le Thanh Ton StreetPhuoc Tien Ward, Nha Trang City',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>49,
                'first_name'     =>'Vũ',
                'last_name'      =>'Đình Văn',
                'birthday'       =>'2010-10-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'3M5IKUQN7S',
                'address'        =>'Str. 10, Song Than 1 IZ.',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],[
                'id'             =>50,
                'first_name'     =>'Trần',
                'last_name'      =>'Đình Sơn',
                'birthday'       =>'2010-10-10',
                'blood_group'    =>'A',
                'gender'         =>1,
                'date_of_joining'=>'2012-02-03',
                'unique_id'      =>'ZECZ3171QH',
                'address'        =>'Room 103, K5 Bach Khoa',
                'allergies'      =>'',
                'additional_note'=>'',
                'image'          =>'',
                'status'         =>1,
                'exist'          =>1,

            ],
        ]);
    }
}
