<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StaffProfilesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('staff_profiles')->delete();
        DB::table('staff_profiles')->insert([
            [
                'id'                =>  1,
                'first_name'        =>  'Dữu',
                'last_name'         =>  'Trường Long',
                'phone'             =>  '0987654321',
                'image'             =>  'Staff1.png',
                'gender'            =>  1,
                'email'             =>  'hellfire@aol.com',
                'address'           =>  '16 Phạm Hùng Nam Từ Liêm Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  2,
                'first_name'        =>  'Phan',
                'last_name'         =>  'Việt Dương',
                'phone'             =>  '0987654322',
                'image'             =>  'Staff2.png',
                'gender'            =>  1,
                'email'             =>  'facet@aol.com',
                'address'           =>  '116 Xuân Thủy Cầu Giấy Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  3,
                'first_name'        =>  'Nguyễn',
                'last_name'         =>  'Khắc Tuấn',
                'phone'             =>  '0987654323',
                'image'             =>  'Staff3.png',
                'gender'            =>  1,
                'email'             =>  'kosact@msn.com',
                'address'           =>  '20 Hàng Trống Hoàn Kiếm Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  4,
                'first_name'        =>  'Trầm',
                'last_name'         =>  'Quốc Trụ',
                'phone'             =>  '0987654324',
                'image'             =>  'Staff4.png',
                'gender'            =>  1,
                'email'             =>  'isaacson@verizon.net',
                'address'           =>  '09 Lê Duẩn Hai Bà Trưng Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  5,
                'first_name'        =>  'Lý',
                'last_name'         =>  'Nhật Hồng',
                'phone'             =>  '0977694322',
                'image'             =>  'Staff5.png',
                'gender'            =>  1,
                'email'             =>  'dhwon@optonline.net',
                'address'           =>  '190 Giải Phóng Hoàng Mai Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  6,
                'first_name'        =>  'Phan',
                'last_name'         =>  'Quốc Bình',
                'phone'             =>  '0923765432',
                'image'             =>  'Staff6.png',
                'gender'            =>  1,
                'email'             =>  'cisugrad@optonline.net',
                'address'           =>  '35 Đông Ngạc Bắc Từ Liêm Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  7,
                'first_name'        =>  'Chung',
                'last_name'         =>  'Bá Thịnh',
                'phone'             =>  '0337654321',
                'image'             =>  'Staff7.png',
                'gender'            =>  1,
                'email'             =>  'grady@icloud.com',
                'address'           =>  '55 Phạm Văn Đồng Cầu Giấy Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  8,
                'first_name'        =>  'Đinh',
                'last_name'         =>  'Thanh Trung',
                'phone'             =>  '0707654321',
                'image'             =>  'Staff8.png',
                'gender'            =>  1,
                'email'             =>  'cisugrad@optonline.net',
                'address'           =>  '44 Hoàng Quốc Việt Cầu Giấy Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  9,
                'first_name'        =>  'Đặng',
                'last_name'         =>  'Hoàng Vương',
                'phone'             =>  '0907354321',
                'image'             =>  'Staff9.png',
                'gender'            =>  1,
                'email'             =>  'grady@icloud.com',
                'address'           =>  '98 Nguyễn Chánh Cầu Giấy Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  10,
                'first_name'        =>  'Lý',
                'last_name'         =>  'Thiện Tâm',
                'phone'             =>  '0867654321',
                'image'             =>  'Staff10.png',
                'gender'            =>  1,
                'email'             =>  'gerlo@att.net',
                'address'           =>  '20 Yên Phụ Tây Hồ Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  11,
                'first_name'        =>  'Lý',
                'last_name'         =>  'Thảo Nguyên',
                'phone'             =>  '0987654456',
                'image'             =>  'Staff11.png',
                'gender'            =>  1,
                'email'             =>  'jguyer@msn.com',
                'address'           =>  '15 Hàng Than Hoàn Kiếm Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  12,
                'first_name'        =>  'Thái',
                'last_name'         =>  'Ái Nhi',
                'phone'             =>  '0587654321',
                'image'             =>  'Staff12.png',
                'gender'            =>  1,
                'email'             =>  'falcao@aol.com',
                'address'           =>  '75 Nguyễn Xiển Thanh Xuân Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  13,
                'first_name'        =>  'Lê',
                'last_name'         =>  'Ánh Dương',
                'phone'             =>  '0967654351',
                'image'             =>  'Staff13.png',
                'gender'            =>  1,
                'email'             =>  'jaffe@outlook.com',
                'address'           =>  '20 Phùng Hưng Hà Đông Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  14,
                'first_name'        =>  'Hoàng',
                'last_name'         =>  'Thục Trang',
                'phone'             =>  '0987987321',
                'image'             =>  'Staff14.png',
                'gender'            =>  1,
                'email'             =>  'yfreund@yahoo.ca',
                'address'           =>  '14 Tố Hữu Thanh Xuân Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  15,
                'first_name'        =>  'Trần',
                'last_name'         =>  'Phương Hiền',
                'phone'             =>  '0937654321',
                'image'             =>  'Staff15.png',
                'gender'            =>  1,
                'email'             =>  'martink@msn.com',
                'address'           =>  '18 Yết Kiêu Hoàn Kiếm Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  16,
                'first_name'        =>  'Dương',
                'last_name'         =>  'Mỹ Huệ',
                'phone'             =>  '0927234321',
                'image'             =>  'Staff16.png',
                'gender'            =>  1,
                'email'             =>  'evans@live.com',
                'address'           =>  '38 Tam Trinh Hoàng Mai Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  17,
                'first_name'        =>  'Chử' ,
                'last_name'         =>  'Giáng Uyên',
                'phone'             =>  '0986734321',
                'image'             =>  'Staff17.png',
                'gender'            =>  1,
                'email'             =>  'thomasj@mac.com',
                'address'           =>  '29 Trần Duy Dưng Cầu Giấy Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  18,
                'first_name'        =>  'Dương',
                'last_name'         =>  'Bích Trang',
                'phone'             =>  '0988654366',
                'image'             =>  'Staff18.png',
                'gender'            =>  1,
                'email'             =>  'sarahs@hotmail.com',
                'address'           =>  '05 Hàng Bồ Hoàn Kiếm Hà Nộ',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  19,
                'first_name'        =>  'Lương',
                'last_name'         =>  'Lệ Thu',
                'phone'             =>  '0867654666',
                'image'             =>  'Staff19.png',
                'gender'            =>  1,
                'email'             =>  'qrczak@hotmail.com',
                'address'           =>  '18 Văn Quán Hà Đông Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
            [
                'id'                =>  20,
                'first_name'        =>  'Ngư',
                'last_name'         =>  'Lan Phương',
                'phone'             =>  '0357654888',
                'image'             =>  'Staff20.png',
                'gender'            =>  1,
                'email'             =>  'preneel@yahoo.ca',
                'address'           =>  '10 Hoàng Quốc Việt Cầu Giấy Hà Nội',
                'birthday'          =>  '1990-12-12',
                'blood_group'       =>  'A',
                'date_of_joining'   =>  '2000-10-10',
            ],
        ]);
    }
}
